apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - helm-rendered.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: myhello
      labels:
        testing: mytest
  target:
    kind: Deployment
    name: hello
    namespace: mycluster-dev